<h3>Whisky Network Reviews - About</h3>

<p>This data was collected from members of the
<a href="#" data-toggle="tooltip" data-placement="top" title="/r/whisky /r/bourbon /r/scotch /r/worldwhisky">Reddit Whisky Network</a>.
This tool is intended to make it easier to search that data. No ownership implied or stated.</p>

<script type="text/javascript">
$('[data-toggle="tooltip"]').tooltip();
</script>
