<br>
<h3 class="text-center"><a href="http://www.reddit.com/u/<?php echo $this->escapeHtml($reviewer); ?>" target="_blank"><?php echo $this->escapeHtml($reviewer); ?></a></h3>
<br>

<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right">Number of Reviews</div>
    <div class="col-xs-6 col-sm-6 col-md-6"><?php echo count($reviews); ?></div>
</div>

<hr>

<?php foreach ($reviews as $review): ?>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right"><?php echo $review->whiskey; ?></div>
    <div class="col-xs-6 col-sm-6 col-md-6"><a target="_blank" href="<?php echo $review->url; ?>"><?php echo $review->rating; ?></a></div>
</div>
<?php endforeach; ?>
