<br>
<h3 class="text-center"><?php echo $this->escapeHtml($search); ?></h3>
<br>

<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right">Number of Reviews</div>
    <div class="col-xs-6 col-sm-6 col-md-6"><?php echo $count; ?></div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right">High Score</div>
    <div class="col-xs-6 col-sm-6 col-md-6"><?php echo $high; ?></div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right">Low Score</div>
    <div class="col-xs-6 col-sm-6 col-md-6"><?php echo $low; ?></div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right">Mean</div>
    <div class="col-xs-6 col-sm-6 col-md-6"><?php echo intval($mean); ?></div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right">Median</div>
    <div class="col-xs-6 col-sm-6 col-md-6"><?php echo intval($median); ?></div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right">Mode</div>
    <div class="col-xs-6 col-sm-6 col-md-6"><?php echo intval($mode); ?></div>
</div>

<hr>

<?php foreach ($matches as $match): ?>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 text-right"><a target="_blank" href="<?php echo $this->url('reviews', array('action' => 'reviewer', 'id' => $match->reviewer)); ?>"><?php echo $match->reviewer; ?></a></div>
    <div class="col-xs-6 col-sm-6 col-md-6"><a target="_blank" href="<?php echo $match->url; ?>"><?php echo $match->rating; ?></a></div>
</div>
<?php endforeach; ?>
