<div class="input-group">
    <span class="input-group-btn">
        <button class="btn btn-default" type="button">Find</button>
    </span>
    <input type="text" id="search" class="form-control" placeholder="texacer">
</div>
<div id="target"></div>
<script type="text/javascript">
$("#search").autocomplete({
    open: function(event, ui) {
        //$('.ui-autocomplete').off('menufocus hover mouseover mouseenter');
        $('.ui-autocomplete').off('mouseenter');
    },
    source: "<?php echo $this->url('reviews', array('action' => 'userautocomplete'));?>",
    minLength: 3,
    select: function(event, ui) {
        console.log(ui.item.label);
        window.location.href = '/reviews/reviewer/' + ui.item.label;
    }
});
</script>
